#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="${1:-$PWD}"

note() {
  printf '%s\n' "$*"
}

remove_path() {
  local p="$1"
  if [[ -e "$p" ]]; then
    rm -f "$p" 2>/dev/null || sudo rm -f "$p"
    note "removed $p"
  fi
}

note "Grove Suite uninstall starting"
note "repo: $REPO_DIR"

# Relay-managed uninstall first (hooks, MCP registrations, tool cache).
if command -v relay >/dev/null 2>&1; then
  relay local uninstall --repo "$REPO_DIR" || true
  relay tools uninstall || true
fi

# Unregister fuse merge driver in the target repo when available.
if command -v fuse >/dev/null 2>&1; then
  (cd "$REPO_DIR" && fuse uninstall) || true
fi

# Remove suite binaries from common install locations.
for p in \
  /usr/local/bin/grove /usr/local/bin/prism /usr/local/bin/fuse /usr/local/bin/relay \
  /opt/homebrew/bin/grove /opt/homebrew/bin/prism /opt/homebrew/bin/fuse /opt/homebrew/bin/relay
 do
  remove_path "$p"
done

# GOPATH/bin fallback for source installs.
if command -v go >/dev/null 2>&1; then
  GOPATH_BIN="$(go env GOPATH 2>/dev/null)/bin"
  for n in grove prism fuse relay; do
    remove_path "$GOPATH_BIN/$n"
  done
fi

# Remove per-user runtime/cache state.
rm -rf "$HOME/.relay" "$HOME/.grove" "$HOME/.prism" "$HOME/.fuse" "$HOME/.cache/prism"
note "removed user cache/state directories"

# Remove project-local state generated by suite tools.
rm -rf "$REPO_DIR/.grove" "$REPO_DIR/.git/fuse"
rm -f "$REPO_DIR/.claude/mcp.json" "$REPO_DIR/.cursor/mcp.json" "$REPO_DIR/.vscode/mcp.json" "$REPO_DIR/.kiro/settings/mcp.json"
note "removed project-local suite state"

# Stop lingering processes.
pkill -f "grove serve" 2>/dev/null || true
pkill -f "prism" 2>/dev/null || true
pkill -f "relay mcp serve" 2>/dev/null || true

note "Grove Suite uninstall complete"
